name: Publish

on:
  push:
    branches:
      - main # Limit deploys to the "main" branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm run build

      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'slp-juney.surge.sh' # Your custom domain (change this!)
          project: 'build' # Deploy the contents of the build dir
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
